In [29]:
import pandas as pd
import numpy as np
from pgmpy.estimators import HillClimbSearch, BicScore, K2Score, BDeuScore
import os

In [30]:
def to_adjascency_mat(edges, numOfNodes):
    
    m = np.zeros((numOfNodes, numOfNodes))
    
    for e in edges:
        i, j = e[0], e[1]
        m[i-1,j-1] = 1
    return m

# Crate target filename and Load data
#dataFile = '../Data/Sachs/1. cd3cd28.xls'
origFolder = 'Small_Datasets'
genProc = 'd5_Gauss_03'
dataFile = os.path.join('..', 'Data', origFolder, genProc, 'data.npy')
fileType = dataFile.split('.')[-1]
# Use appropriate laoding procedure according to file type
if fileType == 'xls':
    df = pd.read_excel(dataFile)
elif fileType == 'npy' or fileType == 'txt':
    data = np.load(dataFile)
    df = pd.DataFrame(data).astype(np.float32)

# Construct columns and normalize them for convergence speed
df.columns = [i for i in range(0, df.shape[1])] # REname columns to numbers for easy of use and readability
#normalized_df=((df-df.min())/(df.max()-df.min())).astype(np.float32)
#print(normalized_df, df.max())
print(df)

            0         1         2          3          4
0    0.591011 -0.571089  0.098601   0.801384  -0.097788
1   -0.398669  1.830743  0.153002  -1.497392   0.951171
2   -0.430361  0.717946  0.940891   0.366309  -0.583918
3    0.387520  0.791294 -0.722450  -0.505728  -0.029472
4   -0.526972  0.191079  1.452063   0.718759  -0.148561
..        ...       ...       ...        ...        ...
995 -1.227067  0.382837  1.900370  -0.763555   3.271972
996  1.323148 -1.260687  5.773150 -20.485466  10.856226
997  0.480042 -2.137227  0.637723  -3.960824   1.188511
998  0.441212  1.452766  2.655661  -6.755983  -1.085593
999  0.567558 -1.243463 -1.613199  15.915068   0.006158

[1000 rows x 5 columns]


In [22]:
# create data sample with 9 random variables:
data = pd.DataFrame(np.random.randint(0, 5, size=(5000, 9)), columns=list('ABCDEFGHI'))

# add 10th dependent variable
data['J'] = data['A'] * data['B']
print(df)
est = HillClimbSearch(data, scoring_method=BicScore(data))
best_model = est.estimate()
print(sorted(best_model.nodes()))
print(best_model.edges())
j = list(best_model.edges())
# search a model with restriction on the number of parents:
# est.estimate(max_indegree=1).edges()




  0%|                                                                                      | 0/1000000 [00:00<?, ?it/s]

        0     1      2       3      4      5      6      7      8     9   \
0     26.4  13.2   8.82   18.30  58.80   6.61  17.00  414.0  17.00  44.9   
1     35.9  16.5  12.30   16.80   8.13  18.60  32.50  352.0   3.37  16.5   
2     59.4  44.1  14.60   10.20  13.00  14.90  32.50  403.0  11.40  31.9   
3     73.0  82.8  23.10   13.50   1.29   5.83  11.80  528.0  13.70  28.6   
4     33.7  19.8   5.19    9.73  24.80  21.10  46.10  305.0   4.66  25.7   
..     ...   ...    ...     ...    ...    ...    ...    ...    ...   ...   
848   42.2  27.6  21.50   67.90  12.30   8.28  15.80  562.0  21.90  29.7   
849   62.1  21.7   9.56    6.49  34.30  15.30  23.10  319.0  11.90  35.5   
850  103.0  32.2  10.20   13.20  50.90   5.28   5.62  239.0  14.50  22.9   
851   77.7  23.7  24.80   60.40  44.50  21.50  25.00  289.0  32.20  83.5   
852   46.6  15.0   8.51  120.00  22.30   6.10  20.00  478.0  20.90  36.8   

        10  
0    40.00  
1    61.50  
2    19.50  
3    23.10  
4    81.30  
..     ..



  0%|                                                                          | 1/1000000 [00:00<264:53:01,  1.05it/s]

  0%|                                                                          | 2/1000000 [00:01<195:10:04,  1.42it/s]

  0%|                                                                          | 3/1000000 [00:01<122:49:51,  2.26it/s]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
[('B', 'A'), ('J', 'B'), ('J', 'A')]


In [33]:
est = HillClimbSearch(df, scoring_method=BDeuScore(df))
best_model = est.estimate(max_iter = 50, max_indegree = 3,epsilon = 0.001)





  0%|                                                                                           | 0/50 [00:00<?, ?it/s]



  2%|█▋                                                                                 | 1/50 [00:02<01:45,  2.14s/it]

MemoryError: Unable to allocate 7.45 GiB for an array with shape (1000000, 1000) and data type float64

In [20]:
print(best_model.edges())
m = list(best_model)

[]


In [9]:
m = to_adjascency_mat(best_model.edges(), 11)
#saveFileBase = './Results/mmhc_sachs_data_1'
saveFileBase = './Results
saveFile = os.path.join(saveFileBase, '_'.join(('mmhc', genProc, 'predG')))
np.save(saveFileBase+'.npy', m)
np.savetxt(saveFileBase, m)
print(m)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
from rpy2.robjects import default_converter
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

# use the default conversion rules to which the pandas conversion
# is added
with localconverter(default_converter + pandas2ri.converter) as cv:
    dataf = robjects.r["data"]