In [2]:
import numpy as np
import os
import pandas as pd
from collections import Counter

In [4]:
fPath = "dummy2.txt"
data = load_data(fPath)
#print(data[data[:,-1] == 'Yes'])

In [14]:
dataDict = count_features_per_class(data)

<ipython-input-13-216b72134e2d>:43: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  keys, freqs = (np.unique(data[[data[:,-1] == c]][:,f], return_counts = True))


In [16]:
comp_feat_entropy(dataDict)

{'a': [2, 1], 'c': [1, 0], 'v': [0, 1], 'z': [1, 0]}
[[2 1]
 [1 0]
 [0 1]
 [1 0]] 6
6
[[1 2]
 [1 0]
 [1 0]
 [1 0]] 6
12
[[1 1]
 [2 0]
 [1 0]
 [0 1]] 6
18
[[2 1]
 [1 0]
 [1 1]] 6
24


In [93]:
dumCLass = [0.1, 0.3, 0.4, 0.2]
compute_entropy(dumCLass)

1.8464393446710154