In [77]:
import pickle as pkl
import pandas as pk
import numpy as np
import networkx as nx
import csv


In [119]:
file = '1. cd3cd28.xls'
graphFile = 'ground_truth_graph.txt'
df = pd.read_excel(file, header = None)

df2 = pd.read_csv(graphFile, header = None)

In [124]:
# Discard Headers and turn to list for storage
table = df.to_numpy()[1:,:].tolist()
graph = df2.values.tolist()
g = np.zeros((11,11))
for i, row in enumerate(graph):
    if i > 0:
        r = row[0].split(' ')[1:]
        r = [float(i) for i in r if i != '']
        print(np.array(r), np.array(r).shape)
        g[i-1,:] = np.array(r)
        
        
print(len(table[1]))

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1.] (11,)
[1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
11


In [121]:
with open('data1.pkl','wb') as f:
    pkl.dump(table, f)
    
with open('data1_graph.pkl','wb') as f:
    pkl.dump(g, f)

In [151]:
dataFolder1 = '../Synthetic_data/gaussian_different_noise_var/'
dataFolder2 = '../Synthetic_data/gaussian_same_noise_var/'
dataFolder3 = '../Synthetic_data/lingam_different_noise_var/'
dataFolder4 = '../Synthetic_data/lingam_same_noise_var/'
dFolders = [dataFolder1, dataFolder2, dataFolder3, dataFolder4 ]

for folder in dFolders:
    cDAG1 = np.load(folder +'DAG.npy')
    data1 = np.load(folder+'data.npy')
    with open(folder+'data.pkl', 'wb') as f:
        pkl.dump(data1, f)
    with open(folder+'data_graph.pkl', 'wb') as f:
        pkl.dump(cDAG1, f)

In [146]:
with open(dataFolder1+'data.pkl', 'wb') as f:
    pkl.dump(data1, f)
with open(dataFolder1+'data_graph.pkl', 'wb') as f:
    pkl.dump(cDAG1, f)

In [147]:
s = np.load('../../src/trueG_halted2.npy')

In [148]:
s

array([[ 0. , -1. ,  0. , -0.6,  0. , -1. ,  0. ,  1.7,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,
         1.4],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1.7,  0. ,  0. ,
        -1.9],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0.9,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  1.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        -1.5],
       [ 0. ,  1.3,  0. ,  0. ,  0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        -1.6],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1.6,  0. ,  0. ,
        -1.4],
       [ 0. ,  0.8,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1.9,  0. ,  0. ,
        -0.9],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ],
       [ 0.8,  0.8,  0. , -1.9,  0. ,  0. , -0.6,  1.1,  1.8,  0. ,  0. ,
         0. ],
       [ 0. ,  0. , -1.5,  0. ,  1.5,  0. ,  2. ,  0. ,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  