In [1]:
import pickle as pkl
import pandas as pk
import numpy as np
import networkx as nx
import csv


In [119]:
file = '1. cd3cd28.xls'
graphFile = 'ground_truth_graph.txt'
df = pd.read_excel(file, header = None)

df2 = pd.read_csv(graphFile, header = None)

In [124]:
# Discard Headers and turn to list for storage
table = df.to_numpy()[1:,:].tolist()
graph = df2.values.tolist()
g = np.zeros((11,11))
for i, row in enumerate(graph):
    if i > 0:
        r = row[0].split(' ')[1:]
        r = [float(i) for i in r if i != '']
        print(np.array(r), np.array(r).shape)
        g[i-1,:] = np.array(r)
        
        
print(len(table[1]))

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[1. 1. 0. 0. 0. 1. 1. 0. 0. 1. 1.] (11,)
[1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (11,)
11


In [121]:
with open('data1.pkl','wb') as f:
    pkl.dump(table, f)
    
with open('data1_graph.pkl','wb') as f:
    pkl.dump(g, f)

In [151]:
dataFolder1 = '../Synthetic_data/gaussian_different_noise_var/'
dataFolder2 = '../Synthetic_data/gaussian_same_noise_var/'
dataFolder3 = '../Synthetic_data/lingam_different_noise_var/'
dataFolder4 = '../Synthetic_data/lingam_same_noise_var/'
dFolders = [dataFolder1, dataFolder2, dataFolder3, dataFolder4 ]

for folder in dFolders:
    cDAG1 = np.load(folder +'DAG.npy')
    data1 = np.load(folder+'data.npy')
    with open(folder+'data.pkl', 'wb') as f:
        pkl.dump(data1, f)
    with open(folder+'data_graph.pkl', 'wb') as f:
        pkl.dump(cDAG1, f)

In [146]:
with open(dataFolder1+'data.pkl', 'wb') as f:
    pkl.dump(data1, f)
with open(dataFolder1+'data_graph.pkl', 'wb') as f:
    pkl.dump(cDAG1, f)

In [147]:
s = np.load('../../src/trueG_halted2.npy')

### Heinze-Deml Conversion

In [5]:
dataFolder1 = '../Heinze-Deml/graph_01/'
dataFolder2 = '../Heinze-Deml/graph_02/'
dataFolder3 = '../Heinze-Deml/graph_03/'
dataFolder4 = '../Heinze-Deml/graph_04/'
dataFolder5 = '../Heinze-Deml/gaussian/'
dataFolder6 = '../Heinze-Deml/hiddenVariables/'
dFolders = [dataFolder1, dataFolder2, dataFolder3, dataFolder4, dataFolder5, dataFolder6 ]

for folder in dFolders:
    cDAG1 = np.load(folder +'DAG.npy')
    data1 = np.load(folder+'data.npy')
    print("Data from {} is of shape: {}".format(folder, data1.shape))
    with open(folder+'data.pkl', 'wb') as f:
        pkl.dump(data1, f)
    with open(folder+'data_graph.pkl', 'wb') as f:
        pkl.dump(cDAG1, f)

Data from ../Heinze-Deml/graph_01/ is of shape: (1000, 12)
Data from ../Heinze-Deml/graph_02/ is of shape: (1000, 12)
Data from ../Heinze-Deml/graph_03/ is of shape: (1000, 12)
Data from ../Heinze-Deml/graph_04/ is of shape: (1000, 12)
Data from ../Heinze-Deml/gaussian/ is of shape: (1000, 12)
Data from ../Heinze-Deml/hiddenVariables/ is of shape: (1000, 12)


In [11]:
d = np.load('../../src/Results/mmhc_sachs_data_1.npy')
np.savetxt('../../src/Results/mmhc_sachs_data_1.txt', d, fmt = '%.3e')

## Small Datasets

In [4]:
dataFolder1 = '../Small_Datasets/d5_Gauss_01/'
dataFolder2 = '../Small_Datasets/d5_Gauss_02/'
dataFolder3 = '../Small_Datasets/d5_Gauss_03/'
dataFolder4 = '../Small_Datasets/d5_nonGauss_01/'
dataFolder5 = '../Small_Datasets/d5_nonGauss_01/'
dataFolder6 = '../Small_Datasets/d5_nonGauss_01/'
dataFolder7 = '../Small_Datasets/d5_nonGauss_hidden_01/'
dataFolder8 = '../Small_Datasets/d5_nonGauss_hidden_02/'
dataFolder9 = '../Small_Datasets/d5_nonGauss_hidden_03/'
dFolders = [dataFolder1, dataFolder2, dataFolder3, dataFolder4, dataFolder5, dataFolder6, dataFolder7, dataFolder8, dataFolder9 ]

for folder in dFolders:
    cDAG1 = np.load(folder +'DAG.npy')
    data1 = np.load(folder+'data.npy')
    print("Data from {} is of shape: {}".format(folder, data1.shape))
    with open(folder+'data.pkl', 'wb') as f:
        pkl.dump(data1, f)
    with open(folder+'data_graph.pkl', 'wb') as f:
        pkl.dump(cDAG1, f)

Data from ../Small_Datasets/d5_Gauss_01/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_Gauss_02/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_Gauss_03/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_nonGauss_01/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_nonGauss_01/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_nonGauss_01/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_nonGauss_hidden_01/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_nonGauss_hidden_02/ is of shape: (1000, 5)
Data from ../Small_Datasets/d5_nonGauss_hidden_03/ is of shape: (1000, 5)
